# name: Build Static Site

# on:
#     push:
#       branches: [ "main" ]
#     pull_request:
#       branches: [ "main" ]

# jobs:
#   Build:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v2
#             - name: Build
#               uses: peaceiris/actions-hugo@v2
#               with:
#                   hugo-version: 'latest'
#                   extended: true
#             - name: Deploy
#               uses: peaceiris/actions-gh-pages@v3
#               with:
#                   github_token: ${{ secrets.GITHUB_TOKEN }}
#                   publish_dir: ./public